# Generated by Django 6.0.1 on 2026-03-31 20:09

import django.db.models.deletion
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_pl', models.CharField(max_length=100, null=True)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('min_age', models.IntegerField(default=0)),
                ('max_age', models.IntegerField(default=99)),
            ],
            options={
                'verbose_name': 'Возрастная группа',
                'verbose_name_plural': 'Возрастные группы',
                'ordering': ['min_age'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_pl', models.CharField(max_length=200, null=True)),
                ('name_en', models.CharField(max_length=200, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('description_pl', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('region', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('title_pl', models.CharField(max_length=500, null=True)),
                ('title_en', models.CharField(max_length=500, null=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('description_pl', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('short_description', models.TextField(blank=True, max_length=500)),
                ('short_description_pl', models.TextField(blank=True, max_length=500, null=True)),
                ('short_description_en', models.TextField(blank=True, max_length=500, null=True)),
                ('event_type', models.CharField(choices=[('spektakl', 'Spektakl'), ('koncert', 'Koncert'), ('festiwal', 'Festiwal'), ('widowisko', 'Widowisko'), ('warsztat', 'Warsztat'), ('inne', 'Inne')], default='spektakl', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('biletyna_base_url', models.URLField(blank=True)),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='events/')),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('age_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.agegroup')),
                ('categories', models.ManyToManyField(blank=True, related_name='events', to='events.category')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'ordering': ['-sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='EventCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('custom_title', models.CharField(blank=True, max_length=500)),
                ('custom_title_pl', models.CharField(blank=True, max_length=500, null=True)),
                ('custom_title_en', models.CharField(blank=True, max_length=500, null=True)),
                ('event_date', models.DateTimeField(blank=True, null=True)),
                ('sale_end_date', models.DateTimeField(blank=True, null=True)),
                ('biletyna_url', models.URLField(blank=True, max_length=500)),
                ('ticket_status', models.CharField(choices=[('available', 'Dostępne'), ('few_left', 'Ostatnie miejsca!'), ('sold_out', 'WYPRZEDANE'), ('upcoming', 'Wkrótce w sprzedaży')], default='available', max_length=20)),
                ('seats_left', models.IntegerField(blank=True, null=True)),
                ('price_from', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=500)),
                ('seo_title_pl', models.CharField(blank=True, max_length=500, null=True)),
                ('seo_title_en', models.CharField(blank=True, max_length=500, null=True)),
                ('seo_description', models.TextField(blank=True)),
                ('seo_description_pl', models.TextField(blank=True, null=True)),
                ('seo_description_en', models.TextField(blank=True, null=True)),
                ('og_image', models.URLField(blank=True, max_length=500)),
                ('canonical_url', models.URLField(blank=True, max_length=500)),
                ('content_html', models.TextField(blank=True)),
                ('content_html_pl', models.TextField(blank=True, null=True)),
                ('content_html_en', models.TextField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_cities', to='events.city')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_cities', to='events.event')),
            ],
            options={
                'verbose_name': 'Событие в городе',
                'verbose_name_plural': 'События в городах',
                'ordering': ['event_date'],
            },
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='events/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=300)),
                ('sort_order', models.IntegerField(default=0)),
                ('event_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='events.eventcity')),
            ],
            options={
                'verbose_name': 'Изображение события',
                'verbose_name_plural': 'Изображения событий',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venues', to='events.city')),
            ],
            options={
                'verbose_name': 'Площадка',
                'verbose_name_plural': 'Площадки',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='eventcity',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_cities', to='events.venue'),
        ),
        migrations.AlterUniqueTogether(
            name='eventcity',
            unique_together={('event', 'city', 'event_date')},
        ),
    ]
