# Generated by Django 6.0.4 on 2026-04-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_seed_categories_agegroups'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Тривалість у хвилинах', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='language_spoken',
            field=models.CharField(blank=True, choices=[('pl', 'Polski'), ('en', 'English'), ('ua', 'Українська'), ('mixed', 'Мішана мова')], max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='target_audience',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='event',
            name='target_audience_en',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='target_audience_pl',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='eventcity',
            name='keywords',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='eventcity',
            name='keywords_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='eventcity',
            name='keywords_pl',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='eventcity',
            name='price_to',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='eventcity',
            name='related_events_manual',
            field=models.ManyToManyField(blank=True, related_name='featured_in_related', to='events.eventcity'),
        ),
    ]
