# Generated by Django 6.0.4 on 2026-04-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_hero_image_focal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='hero_image_focal',
            field=models.CharField(choices=[('top', 'Top'), ('center', 'Center'), ('bottom', 'Bottom')], default='center', help_text='Vertical crop focus for the event detail hero image (object-position).', max_length=20),
        ),
    ]
