# Generated by Django 6.0.4 on 2026-04-13 13:50

import django.db.models.deletion
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_hero_focal_top_to_center_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcity',
            name='use_new_layout',
            field=models.BooleanField(default=False, help_text='Увімкнути структурований layout (контент-блоки, відео-, фото-галерея). Старий content_html ігнорується.'),
        ),
        migrations.CreateModel(
            name='EventContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500)),
                ('title_pl', models.CharField(blank=True, max_length=500, null=True)),
                ('title_en', models.CharField(blank=True, max_length=500, null=True)),
                ('body', models.TextField(blank=True)),
                ('body_pl', models.TextField(blank=True, null=True)),
                ('body_en', models.TextField(blank=True, null=True)),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='events/blocks/')),
                ('button_text', models.CharField(blank=True, max_length=200)),
                ('button_text_pl', models.CharField(blank=True, max_length=200, null=True)),
                ('button_text_en', models.CharField(blank=True, max_length=200, null=True)),
                ('button_url', models.URLField(blank=True, max_length=500)),
                ('sort_order', models.IntegerField(default=0)),
                ('event_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='events.eventcity')),
            ],
            options={
                'verbose_name': 'Блок контенту події',
                'verbose_name_plural': 'Блоки контенту події',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='EventVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embed_url', models.URLField(help_text='Повний embed-URL (YouTube /embed/…, Vimeo player.vimeo.com/…)', max_length=500)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('sort_order', models.IntegerField(default=0)),
                ('event_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='events.eventcity')),
            ],
            options={
                'verbose_name': 'Відео події',
                'verbose_name_plural': 'Відео подій',
                'ordering': ['sort_order'],
            },
        ),
    ]
