# Generated by Django 6.0.4 on 2026-04-14 11:07

import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_eventcity_use_new_layout_eventcontentblock_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventimage',
            options={'ordering': ['sort_order'], 'verbose_name': 'Zdjęcie galerii', 'verbose_name_plural': 'Galeria zdjęć (dodaj wiele zdjęć tutaj)'},
        ),
        migrations.AddField(
            model_name='eventimage',
            name='image_url',
            field=models.URLField(blank=True, help_text='Альтернативно до файлу: вставте пряме URL зображення', max_length=500),
        ),
        migrations.AddField(
            model_name='eventvideo',
            name='video_file',
            field=models.FileField(blank=True, help_text="Альтернативно до URL: завантажте відеофайл з комп'ютера (mp4/webm)", null=True, upload_to='events/videos/'),
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='events/gallery/'),
        ),
        migrations.AlterField(
            model_name='eventvideo',
            name='embed_url',
            field=models.URLField(blank=True, help_text='Embed-URL (YouTube /embed/…, Vimeo player.vimeo.com/…)', max_length=500),
        ),
    ]
