# Generated by Django 6.0.4 on 2026-04-20 09:21

import django.db.models.deletion
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_image_url_video_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agegroup',
            options={'ordering': ['min_age'], 'verbose_name': 'Grupa wiekowa (Вікова група)', 'verbose_name_plural': 'Grupy wiekowe (Вікові групи)'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Kategoria (Категорія)', 'verbose_name_plural': 'Kategorie (Категорії)'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name': 'Miasto (Місто)', 'verbose_name_plural': 'Miasta (Міста)'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-sort_order', 'title'], 'verbose_name': 'Wydarzenie (Подія)', 'verbose_name_plural': 'Wydarzenia (Події)'},
        ),
        migrations.AlterModelOptions(
            name='eventcity',
            options={'ordering': ['event_date'], 'verbose_name': 'Wydarzenie w mieście (Подія в місті)', 'verbose_name_plural': 'Wydarzenia w miastach (Події в містах)'},
        ),
        migrations.AlterModelOptions(
            name='eventcontentblock',
            options={'ordering': ['sort_order'], 'verbose_name': 'Blok treści wydarzenia (Блок контенту події)', 'verbose_name_plural': 'Bloki treści wydarzeń (Блоки контенту подій)'},
        ),
        migrations.AlterModelOptions(
            name='eventimage',
            options={'ordering': ['sort_order'], 'verbose_name': 'Zdjęcie galerii (Фото галереї)', 'verbose_name_plural': 'Galeria zdjęć (dodaj wiele — pojawi się na stronie) (Галерея фото (додайте кілька — з’явиться на сайті))'},
        ),
        migrations.AlterModelOptions(
            name='eventvideo',
            options={'ordering': ['sort_order'], 'verbose_name': 'Wideo wydarzenia (Відео події)', 'verbose_name_plural': 'Wideo wydarzeń (Відео подій)'},
        ),
        migrations.AlterModelOptions(
            name='venue',
            options={'ordering': ['name'], 'verbose_name': 'Miejsce (Місце проведення)', 'verbose_name_plural': 'Miejsca (Місця проведення)'},
        ),
        migrations.AlterField(
            model_name='agegroup',
            name='max_age',
            field=models.IntegerField(default=99, verbose_name='Wiek maks. (Макс. вік)'),
        ),
        migrations.AlterField(
            model_name='agegroup',
            name='min_age',
            field=models.IntegerField(default=0, verbose_name='Wiek min. (Мін. вік)'),
        ),
        migrations.AlterField(
            model_name='agegroup',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nazwa (Назва)'),
        ),
        migrations.AlterField(
            model_name='agegroup',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Nazwa (Назва)'),
        ),
        migrations.AlterField(
            model_name='agegroup',
            name='name_pl',
            field=models.CharField(max_length=100, null=True, verbose_name='Nazwa (Назва)'),
        ),
        migrations.AlterField(
            model_name='agegroup',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug (Слаг)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='Opis (Опис)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Opis (Опис)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description_pl',
            field=models.TextField(blank=True, null=True, verbose_name='Opis (Опис)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ikona (Іконка)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nazwa (Назва)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Nazwa (Назва)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_pl',
            field=models.CharField(max_length=200, null=True, verbose_name='Nazwa (Назва)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug (Слаг)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='Kolejność (Порядок)'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nazwa (Назва)'),
        ),
        migrations.AlterField(
            model_name='city',
            name='region',
            field=models.CharField(blank=True, max_length=200, verbose_name='Region (Регіон)'),
        ),
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug (Слаг)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='age_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.agegroup', verbose_name='Grupa wiekowa (Вікова група)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='biletyna_base_url',
            field=models.URLField(blank=True, verbose_name='Bazowy URL Biletyna (Базовий URL Biletyna)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='events', to='events.category', verbose_name='Kategorie (Категорії)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Utworzono (Створено)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, verbose_name='Opis (Опис)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Opis (Опис)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description_pl',
            field=models.TextField(blank=True, null=True, verbose_name='Opis (Опис)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Czas trwania w minutach (Тривалість у хвилинах)', null=True, verbose_name='Czas trwania (min) (Тривалість (хв))'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('spektakl', 'Spektakl'), ('koncert', 'Koncert'), ('festiwal', 'Festiwal'), ('widowisko', 'Widowisko'), ('warsztat', 'Warsztat'), ('inne', 'Inne')], default='spektakl', max_length=50, verbose_name='Typ wydarzenia (Тип події)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='hero_image_focal',
            field=models.CharField(choices=[('top', 'Top'), ('center', 'Center'), ('bottom', 'Bottom')], default='center', help_text='Pionowe kadrowanie obrazu bohatera (object-position) (Вертикальне кадрування зображення героя (object-position))', max_length=20, verbose_name='Ostrość obrazu bohatera (Фокус зображення героя)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='events/', verbose_name='Obraz (Зображення)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktywne (Активна)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='language_spoken',
            field=models.CharField(blank=True, choices=[('pl', 'Polski'), ('en', 'English'), ('ua', 'Українська'), ('mixed', 'Мішана мова')], max_length=10, verbose_name='Język (Мова)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='short_description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Krótki opis (Короткий опис)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='short_description_en',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Krótki opis (Короткий опис)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='short_description_pl',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Krótki opis (Короткий опис)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Slug (Слаг)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='Kolejność (Порядок)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='target_audience',
            field=models.CharField(blank=True, max_length=300, verbose_name='Grupa docelowa (Цільова аудиторія)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='target_audience_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Grupa docelowa (Цільова аудиторія)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='target_audience_pl',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Grupa docelowa (Цільова аудиторія)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Tytuł (Заголовок)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Tytuł (Заголовок)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title_pl',
            field=models.CharField(max_length=500, null=True, verbose_name='Tytuł (Заголовок)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano (Оновлено)'),
        ),
        migrations.AlterField(
            model_name='eventcity',
            name='biletyna_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL Biletyna (URL Biletyna)'),
        ),
        migrations.AlterField(
            model_name='eventcity',
            name='canonical_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL kanoniczny (Канонічний URL)'),
        ),
        migrations.AlterField(
            model_name='eventcity',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_cities', to='events.city', verbose_name='Miasto (Місто)'),
        ),
        migrations.AlterField(
            model_name='eventcity',
            name='content_html',
            field=models.TextField(blank=True, verbose_name='Treść HTML (Вміст HTML)'),
        ),
        migrations.AlterField(
            model_name='eventcity',
            name='content_html_en',
            field=models.TextField(blank=True, null=True, verbose_name='Treść HTML (Вміст HTML)'),
        ),
        migrations.AlterField(
            model_name='eventcity',
            name='content_html_pl',
            field=models.TextField(blank=True, null=True, verbose_name='Treść HTML (Вміст HTML)'),
        ),
        migrations.AlterField(
            model_name='eventcity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Utworzono (Створено)'),
        ),
        migrations.AlterField(
            model_name='eventcity',
            name='custom_title',
            field=models.CharField(blank=True, max_length=500, verbose_name='Niestandardowy tytuł (Власний заголовок)'),
        ),
        migrations.AlterField(
            model_name='eventcity',
            name='custom_title_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Niestandardowy tytuł (Власний заголовок)'),
        ),
        migrations.AlterField(
            model_name='eventcity',
            name='custom_title_pl',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Niestandardowy tytuł (Власний заголовок)'),
        ),
        migrations.AlterField(
            model_name='eventcity',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_cities', to='events.event', verbose_name='Wydarzenie (Подія)'),
        ),
        migrations.AlterField(
            model_name='eventcity',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data wydarzenia (Дата події)'),
        ),
        migrations.AlterField(
            model_name='eventcity',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Opublikowane (Опубліковано)'),
        ),
        migrations.AlterField(
            model_name='eventcity',
            name='keywords',
            field=models.CharField(blank=True, max_length=500, verbose_name='Słowa kluczowe (Ключові слова)'),
        ),
        migrations.AlterField(
            model_name='eventcity',
            name='keywords_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Słowa kluczowe (Ключові слова)'),
        ),
        migrations.AlterField(
            model_name='eventcity',
            name='keywords_pl',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Słowa kluczowe (Ключові слова)'),
        ),
        migrations.AlterField(
            model_name='eventcity',
            name='og_image',
            field=models.URLField(blank=True, max_length=500, verbose_name='Obraz OG (OG-зображення)'),
        ),
        migrations.AlterField(
            model_name='eventcity',
            name='price_from',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cena od (Ціна від)'),
        ),
        migrations.AlterField(
            model_name='eventcity',
            name='price_to',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cena do (Ціна до)'),
        ),
        migrations.AlterField(
            model_name='eventcity',
            name='related_events_manual',
            field=models.ManyToManyField(blank=True, related_name='featured_in_related', to='events.eventcity', verbose_name='Powiązane wydarzenia (ręcznie) (Пов’язані події (вручну))'),
        ),
        migrations.AlterField(
            model_name='eventcity',
            name='sale_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Koniec sprzedaży (Кінець продажу)'),
        ),
        migrations.AlterField(
            model_name='eventcity',
            name='seats_left',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pozostałe miejsca (Залишок місць)'),
        ),
        migrations.AlterField(
            model_name='eventcity',
            name='seo_description',
            field=models.TextField(blank=True, verbose_name='Opis SEO (SEO-опис)'),
        ),
        migrations.AlterField(
            model_name='eventcity',
            name='seo_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Opis SEO (SEO-опис)'),
        ),
        migrations.AlterField(
            model_name='eventcity',
            name='seo_description_pl',
            field=models.TextField(blank=True, null=True, verbose_name='Opis SEO (SEO-опис)'),
        ),
        migrations.AlterField(
            model_name='eventcity',
            name='seo_title',
            field=models.CharField(blank=True, max_length=500, verbose_name='Tytuł SEO (SEO-заголовок)'),
        ),
        migrations.AlterField(
            model_name='eventcity',
            name='seo_title_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Tytuł SEO (SEO-заголовок)'),
        ),
        migrations.AlterField(
            model_name='eventcity',
            name='seo_title_pl',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Tytuł SEO (SEO-заголовок)'),
        ),
        migrations.AlterField(
            model_name='eventcity',
            name='slug',
            field=models.SlugField(max_length=300, unique=True, verbose_name='Slug (Слаг)'),
        ),
        migrations.AlterField(
            model_name='eventcity',
            name='ticket_status',
            field=models.CharField(choices=[('available', 'Dostępne'), ('few_left', 'Ostatnie miejsca!'), ('sold_out', 'WYPRZEDANE'), ('upcoming', 'Wkrótce w sprzedaży')], default='available', max_length=20, verbose_name='Status biletów (Статус квитків)'),
        ),
        migrations.AlterField(
            model_name='eventcity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano (Оновлено)'),
        ),
        migrations.AlterField(
            model_name='eventcity',
            name='use_new_layout',
            field=models.BooleanField(default=False, help_text='Układ strukturalny (bloki treści, wideo, galeria). Stary HTML jest ignorowany. (Структурований макет (блоки контенту, відео, галерея). Старий HTML ігнорується.)', verbose_name='Nowy układ strony (Новий макет сторінки)'),
        ),
        migrations.AlterField(
            model_name='eventcity',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_cities', to='events.venue', verbose_name='Miejsce (Місце)'),
        ),
        migrations.AlterField(
            model_name='eventcontentblock',
            name='body',
            field=models.TextField(blank=True, verbose_name='Treść (Вміст)'),
        ),
        migrations.AlterField(
            model_name='eventcontentblock',
            name='body_en',
            field=models.TextField(blank=True, null=True, verbose_name='Treść (Вміст)'),
        ),
        migrations.AlterField(
            model_name='eventcontentblock',
            name='body_pl',
            field=models.TextField(blank=True, null=True, verbose_name='Treść (Вміст)'),
        ),
        migrations.AlterField(
            model_name='eventcontentblock',
            name='button_text',
            field=models.CharField(blank=True, max_length=200, verbose_name='Tekst przycisku (Текст кнопки)'),
        ),
        migrations.AlterField(
            model_name='eventcontentblock',
            name='button_text_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tekst przycisku (Текст кнопки)'),
        ),
        migrations.AlterField(
            model_name='eventcontentblock',
            name='button_text_pl',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tekst przycisku (Текст кнопки)'),
        ),
        migrations.AlterField(
            model_name='eventcontentblock',
            name='button_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL przycisku (URL кнопки)'),
        ),
        migrations.AlterField(
            model_name='eventcontentblock',
            name='event_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='events.eventcity', verbose_name='Wydarzenie w mieście (Подія в місті)'),
        ),
        migrations.AlterField(
            model_name='eventcontentblock',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='events/blocks/', verbose_name='Obraz (Зображення)'),
        ),
        migrations.AlterField(
            model_name='eventcontentblock',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='Kolejność (Порядок)'),
        ),
        migrations.AlterField(
            model_name='eventcontentblock',
            name='title',
            field=models.CharField(blank=True, max_length=500, verbose_name='Tytuł (Заголовок)'),
        ),
        migrations.AlterField(
            model_name='eventcontentblock',
            name='title_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Tytuł (Заголовок)'),
        ),
        migrations.AlterField(
            model_name='eventcontentblock',
            name='title_pl',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Tytuł (Заголовок)'),
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=300, verbose_name='Tekst alternatywny (Альтернативний текст)'),
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='event_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='events.eventcity', verbose_name='Wydarzenie w mieście (Подія в місті)'),
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='events/gallery/', verbose_name='Obraz (Зображення)'),
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='image_url',
            field=models.URLField(blank=True, help_text='Zamiast pliku: bezpośredni URL obrazu (Замість файлу: пряме URL зображення)', max_length=500, verbose_name='URL obrazu (URL зображення)'),
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='Kolejność (Порядок)'),
        ),
        migrations.AlterField(
            model_name='eventvideo',
            name='embed_url',
            field=models.URLField(blank=True, help_text='URL do osadzenia (YouTube /embed/…, Vimeo player.vimeo.com/…) (URL для вбудовування (YouTube /embed/…, Vimeo …))', max_length=500, verbose_name='URL osadzenia (URL вбудовування)'),
        ),
        migrations.AlterField(
            model_name='eventvideo',
            name='event_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='events.eventcity', verbose_name='Wydarzenie w mieście (Подія в місті)'),
        ),
        migrations.AlterField(
            model_name='eventvideo',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='Kolejność (Порядок)'),
        ),
        migrations.AlterField(
            model_name='eventvideo',
            name='title',
            field=models.CharField(blank=True, max_length=300, verbose_name='Tytuł (Заголовок)'),
        ),
        migrations.AlterField(
            model_name='eventvideo',
            name='video_file',
            field=models.FileField(blank=True, help_text='Zamiast URL: plik wideo z komputera (mp4/webm) (Замість URL: відеофайл з комп’ютера (mp4/webm))', null=True, upload_to='events/videos/', verbose_name='Plik wideo (Відеофайл)'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='address',
            field=models.CharField(blank=True, max_length=500, verbose_name='Adres (Адреса)'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venues', to='events.city', verbose_name='Miasto (Місто)'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Szer. geogr. (Широта)'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Dł. geogr. (Довгота)'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Nazwa (Назва)'),
        ),
    ]
