# Generated by Django 6.0.4 on 2026-04-20 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_admin_labels_pl_uk'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcity',
            name='use_block_builder',
            field=models.BooleanField(default=False, help_text='Renderuj stronę z konstruktora bloków (CMS). Pomija stary układ. (Рендерити сторінку з блок-конструктора (CMS). Ігнорує старий макет.)', verbose_name='Konstruktor bloków (CMS) (Блок-конструктор (CMS))'),
        ),
    ]
