# Generated by Django 6.0.4 on 2026-04-21 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_add_event_archival'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcity',
            name='archive_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Data archiwizacji (Дата архівації)'),
        ),
        migrations.AlterField(
            model_name='eventcity',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Zarchiwizowane (Заархівоване)'),
        ),
    ]
