# Generated by Django 6.0.4 on 2026-04-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_alter_eventcity_archive_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hero_video_autoplay',
            field=models.BooleanField(default=True, help_text='Automatyczne odtwarzanie wideo (wymagane muted=True dla polityk przeglądarki) (Автоматичне відтворення відео (вимагає muted=True для політик браузера))', verbose_name='Autoplay wideo (Автовідтворення відео)'),
        ),
        migrations.AddField(
            model_name='event',
            name='hero_video_embed_url',
            field=models.URLField(blank=True, help_text='Zamiast pliku: URL do osadzenia wideo (YouTube /embed/…, Vimeo …) (Замість файлу: URL для вбудовування відео (YouTube /embed/…, Vimeo …))', max_length=500, verbose_name='URL osadzenia wideo (URL вбудовування відео)'),
        ),
        migrations.AddField(
            model_name='event',
            name='hero_video_file',
            field=models.FileField(blank=True, help_text='Plik wideo (mp4/webm) jako tło szapki. Będzie odtwarzany w pełnej szerokości. (Відеофайл (mp4/webm) як фонове відео шапки. Буде відтворюватися на весь екран.)', null=True, upload_to='events/videos/', verbose_name='Wideo героя (Відео героя)'),
        ),
        migrations.AddField(
            model_name='event',
            name='hero_video_muted',
            field=models.BooleanField(default=True, help_text='Wyciszenie wideo (wymagane dla autoplay) (Вимкнення звуку видео (вимагається для autoplay))', verbose_name='Wyciszenie wideo (Вимкнення звуку)'),
        ),
    ]
