# Generated by Django 6.0.1 on 2026-03-31 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('name_pl', models.CharField(max_length=300, null=True)),
                ('name_en', models.CharField(max_length=300, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('description_pl', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='PLN', max_length=3)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vouchers/')),
                ('purchase_url', models.URLField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Ваучер',
                'verbose_name_plural': 'Ваучеры',
                'ordering': ['sort_order', 'price'],
            },
        ),
    ]
