# Generated by Django 6.0.4 on 2026-04-16 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payu_order_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Oczekuje'), ('WAITING_FOR_CONFIRMATION', 'Oczekuje na potwierdzenie'), ('COMPLETED', 'Opłacono'), ('CANCELED', 'Anulowano')], default='PENDING', max_length=30)),
                ('buyer_first_name', models.CharField(max_length=100)),
                ('buyer_last_name', models.CharField(max_length=100)),
                ('buyer_email', models.EmailField(max_length=254)),
                ('buyer_phone', models.CharField(blank=True, max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='vouchers.voucher')),
            ],
            options={
                'verbose_name': 'Zamówienie vouchera',
                'verbose_name_plural': 'Zamówienia voucherów',
                'ordering': ['-created_at'],
            },
        ),
    ]
