# Generated by Django 6.0.4 on 2026-04-20 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0003_fix_bossbarboss_voucher_image_path'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voucher',
            options={'ordering': ['sort_order', 'price'], 'verbose_name': 'Voucher (Ваучер)', 'verbose_name_plural': 'Vouchery (Ваучери)'},
        ),
        migrations.AlterModelOptions(
            name='voucherorder',
            options={'ordering': ['-created_at'], 'verbose_name': 'Zamówienie vouchera (Замовлення ваучера)', 'verbose_name_plural': 'Zamówienia voucherów (Замовлення ваучерів)'},
        ),
        migrations.AlterField(
            model_name='voucher',
            name='currency',
            field=models.CharField(default='PLN', max_length=3, verbose_name='Waluta (Валюта)'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='description',
            field=models.TextField(blank=True, verbose_name='Opis (Опис)'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Opis (Опис)'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='description_pl',
            field=models.TextField(blank=True, null=True, verbose_name='Opis (Опис)'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='vouchers/', verbose_name='Obraz (Зображення)'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktywny (Активний)'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Nazwa (Назва)'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='name_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Nazwa (Назва)'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='name_pl',
            field=models.CharField(max_length=300, null=True, verbose_name='Nazwa (Назва)'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena (Ціна)'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='purchase_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL zakupu (URL покупки)'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug (Слаг)'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='Kolejność (Порядок)'),
        ),
        migrations.AlterField(
            model_name='voucherorder',
            name='buyer_email',
            field=models.EmailField(max_length=254, verbose_name='E-mail kupującego (Email покупця)'),
        ),
        migrations.AlterField(
            model_name='voucherorder',
            name='buyer_first_name',
            field=models.CharField(max_length=100, verbose_name='Imię kupującego (Ім’я покупця)'),
        ),
        migrations.AlterField(
            model_name='voucherorder',
            name='buyer_last_name',
            field=models.CharField(max_length=100, verbose_name='Nazwisko kupującego (Прізвище покупця)'),
        ),
        migrations.AlterField(
            model_name='voucherorder',
            name='buyer_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefon kupującego (Телефон покупця)'),
        ),
        migrations.AlterField(
            model_name='voucherorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Utworzono (Створено)'),
        ),
        migrations.AlterField(
            model_name='voucherorder',
            name='payu_order_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='ID zamówienia PayU (ID замовлення PayU)'),
        ),
        migrations.AlterField(
            model_name='voucherorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Oczekuje'), ('WAITING_FOR_CONFIRMATION', 'Oczekuje na potwierdzenie'), ('COMPLETED', 'Opłacono'), ('CANCELED', 'Anulowano')], default='PENDING', max_length=30, verbose_name='Status (Статус)'),
        ),
        migrations.AlterField(
            model_name='voucherorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kwota (Сума)'),
        ),
        migrations.AlterField(
            model_name='voucherorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano (Оновлено)'),
        ),
        migrations.AlterField(
            model_name='voucherorder',
            name='voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='vouchers.voucher', verbose_name='Voucher (Ваучер)'),
        ),
    ]
