# Generated by Django 6.0.4 on 2026-04-20 09:21

import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_keywords_article_keywords_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_at'], 'verbose_name': 'Artykuł (Стаття)', 'verbose_name_plural': 'Artykuły (Статті)'},
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(verbose_name='Treść (Вміст)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Treść (Вміст)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content_pl',
            field=models.TextField(null=True, verbose_name='Treść (Вміст)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Utworzono (Створено)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='excerpt',
            field=models.TextField(blank=True, max_length=500, verbose_name='Zajawka (Анонс)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='excerpt_en',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Zajawka (Анонс)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='excerpt_pl',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Zajawka (Анонс)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='blog/', verbose_name='Obraz (Зображення)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Opublikowane (Опубліковано)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='keywords',
            field=models.CharField(blank=True, max_length=500, verbose_name='Słowa kluczowe (Ключові слова)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='keywords_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Słowa kluczowe (Ключові слова)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='keywords_pl',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Słowa kluczowe (Ключові слова)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='og_image',
            field=models.URLField(blank=True, max_length=500, verbose_name='Obraz OG (OG-зображення)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data publikacji (Дата публікації)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='seo_description',
            field=models.TextField(blank=True, verbose_name='Opis SEO (SEO-опис)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='seo_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Opis SEO (SEO-опис)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='seo_description_pl',
            field=models.TextField(blank=True, null=True, verbose_name='Opis SEO (SEO-опис)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='seo_title',
            field=models.CharField(blank=True, max_length=500, verbose_name='Tytuł SEO (SEO-заголовок)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='seo_title_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Tytuł SEO (SEO-заголовок)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='seo_title_pl',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Tytuł SEO (SEO-заголовок)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(max_length=300, unique=True, verbose_name='Slug (Слаг)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Tytuł (Заголовок)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Tytuł (Заголовок)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_pl',
            field=models.CharField(max_length=500, null=True, verbose_name='Tytuł (Заголовок)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano (Оновлено)'),
        ),
    ]
