# Generated by Django 6.0.4 on 2026-04-20 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_admin_labels_pl_uk'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='canonical_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL kanoniczny (Канонічний URL)'),
        ),
        migrations.AddField(
            model_name='article',
            name='robots_directives',
            field=models.CharField(blank=True, help_text='Np. noindex,nofollow — pozostaw puste dla domyślnych (Напр. noindex,nofollow — залиш порожнім для дефолтних)', max_length=100, verbose_name='Dyrektywy robots (Директиви robots)'),
        ),
        migrations.AddField(
            model_name='article',
            name='use_block_builder',
            field=models.BooleanField(default=False, help_text='Użyj nowego konstruktora bloków (CMS). Stary HTML jest ignorowany. (Використати новий блок-конструктор (CMS). Старий HTML ігнорується.)', verbose_name='Konstruktor bloków (CMS) (Блок-конструктор (CMS))'),
        ),
    ]
