# Generated by Django 6.0.4 on 2026-04-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='redirect',
            options={'verbose_name': 'Przekierowanie (Редирект)', 'verbose_name_plural': 'Przekierowania (Редиректи)'},
        ),
        migrations.AlterField(
            model_name='redirect',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Utworzono (Створено)'),
        ),
        migrations.AlterField(
            model_name='redirect',
            name='new_path',
            field=models.CharField(max_length=500, verbose_name='Nowy adres (ścieżka) (Нова адреса (шлях))'),
        ),
        migrations.AlterField(
            model_name='redirect',
            name='old_path',
            field=models.CharField(db_index=True, max_length=500, unique=True, verbose_name='Stary adres (ścieżka) (Стара адреса (шлях))'),
        ),
    ]
