# Generated by Django 6.0.1 on 2026-03-31 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('title_pl', models.CharField(max_length=500, null=True)),
                ('title_en', models.CharField(max_length=500, null=True)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('content', models.TextField()),
                ('content_pl', models.TextField(null=True)),
                ('content_en', models.TextField(null=True)),
                ('seo_title', models.CharField(blank=True, max_length=500)),
                ('seo_title_pl', models.CharField(blank=True, max_length=500, null=True)),
                ('seo_title_en', models.CharField(blank=True, max_length=500, null=True)),
                ('seo_description', models.TextField(blank=True)),
                ('seo_description_pl', models.TextField(blank=True, null=True)),
                ('seo_description_en', models.TextField(blank=True, null=True)),
                ('show_contact_form', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Статическая страница',
                'verbose_name_plural': 'Статические страницы',
                'ordering': ['sort_order'],
            },
        ),
    ]
