# Generated by Django 6.0.4 on 2026-04-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticpage',
            name='keywords',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='keywords_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='keywords_pl',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='page_type',
            field=models.CharField(choices=[('static', 'Статична сторінка'), ('landing', 'Лендінг')], default='static', max_length=20),
        ),
    ]
