# Generated by Django 6.0.4 on 2026-04-17 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_staticpage_layout_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('image', 'Zdjęcie'), ('video', 'Wideo')], default='image', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pages/media/')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='pages/media/')),
                ('video_embed_url', models.URLField(blank=True)),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('caption_pl', models.CharField(blank=True, max_length=300, null=True)),
                ('caption_en', models.CharField(blank=True, max_length=300, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='pages.staticpage')),
            ],
            options={
                'verbose_name': 'Медіа сторінки',
                'verbose_name_plural': 'Медіа сторінок',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
