# Generated by Django 6.0.4 on 2026-04-20 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_remove_layout_version_v2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagemedia',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'Media strony (Медіа сторінки)', 'verbose_name_plural': 'Media stron (Медіа сторінок)'},
        ),
        migrations.AlterModelOptions(
            name='staticpage',
            options={'ordering': ['sort_order'], 'verbose_name': 'Strona statyczna (Статична сторінка)', 'verbose_name_plural': 'Strony statyczne (Статичні сторінки)'},
        ),
        migrations.AlterField(
            model_name='pagemedia',
            name='caption',
            field=models.CharField(blank=True, max_length=300, verbose_name='Podpis (Підпис)'),
        ),
        migrations.AlterField(
            model_name='pagemedia',
            name='caption_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Podpis (Підпис)'),
        ),
        migrations.AlterField(
            model_name='pagemedia',
            name='caption_pl',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Podpis (Підпис)'),
        ),
        migrations.AlterField(
            model_name='pagemedia',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pages/media/', verbose_name='Obraz (Зображення)'),
        ),
        migrations.AlterField(
            model_name='pagemedia',
            name='kind',
            field=models.CharField(choices=[('image', 'Zdjęcie'), ('video', 'Wideo')], default='image', max_length=10, verbose_name='Rodzaj (Тип)'),
        ),
        migrations.AlterField(
            model_name='pagemedia',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='pages.staticpage', verbose_name='Strona (Сторінка)'),
        ),
        migrations.AlterField(
            model_name='pagemedia',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='Kolejność (Порядок)'),
        ),
        migrations.AlterField(
            model_name='pagemedia',
            name='video_embed_url',
            field=models.URLField(blank=True, verbose_name='URL osadzenia wideo (URL вбудовування відео)'),
        ),
        migrations.AlterField(
            model_name='pagemedia',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='pages/media/', verbose_name='Plik wideo (Відеофайл)'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='content',
            field=models.TextField(verbose_name='Treść (Вміст)'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Treść (Вміст)'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='content_pl',
            field=models.TextField(null=True, verbose_name='Treść (Вміст)'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Utworzono (Створено)'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Opublikowane (Опубліковано)'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='keywords',
            field=models.CharField(blank=True, max_length=500, verbose_name='Słowa kluczowe (Ключові слова)'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='keywords_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Słowa kluczowe (Ключові слова)'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='keywords_pl',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Słowa kluczowe (Ключові слова)'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='layout_version',
            field=models.CharField(choices=[('v1', 'Класична')], default='v1', max_length=10, verbose_name='Wersja układu (Версія макета)'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='page_type',
            field=models.CharField(choices=[('static', 'Статична сторінка'), ('landing', 'Лендінг')], default='static', max_length=20, verbose_name='Typ strony (Тип сторінки)'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='seo_description',
            field=models.TextField(blank=True, verbose_name='Opis SEO (SEO-опис)'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='seo_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Opis SEO (SEO-опис)'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='seo_description_pl',
            field=models.TextField(blank=True, null=True, verbose_name='Opis SEO (SEO-опис)'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='seo_title',
            field=models.CharField(blank=True, max_length=500, verbose_name='Tytuł SEO (SEO-заголовок)'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='seo_title_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Tytuł SEO (SEO-заголовок)'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='seo_title_pl',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Tytuł SEO (SEO-заголовок)'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='show_contact_form',
            field=models.BooleanField(default=False, verbose_name='Pokaż formularz kontaktowy (Показати форму контакту)'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='slug',
            field=models.SlugField(max_length=300, unique=True, verbose_name='Slug (Слаг)'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='Kolejność (Порядок)'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Tytuł (Заголовок)'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='title_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Tytuł (Заголовок)'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='title_pl',
            field=models.CharField(max_length=500, null=True, verbose_name='Tytuł (Заголовок)'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano (Оновлено)'),
        ),
    ]
