# Generated by Django 6.0.4 on 2026-04-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_admin_labels_pl_uk'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent', models.CharField(choices=[('repertuar', 'Repertuar'), ('rezerwacja', 'Rezerwacja biletów'), ('specjalna_oferta', 'Oferta specjalna'), ('event_firmowy', 'Event / wyjazd'), ('voucher', 'Voucher / prezent'), ('other', 'Inne')], db_index=True, max_length=32)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('company', models.CharField(blank=True, max_length=300)),
                ('nip', models.CharField(blank=True, max_length=20)),
                ('ticket_count', models.CharField(blank=True, max_length=50)),
                ('message', models.TextField()),
                ('source_page', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('handled', models.BooleanField(default=False, verbose_name='Obsłużone (Опрацьовано)')),
                ('staff_notes', models.TextField(blank=True, verbose_name='Notatki wewnętrzne (Внутрішні нотатки)')),
            ],
            options={
                'verbose_name': 'Zgłoszenie grupowe (Групова заявка)',
                'verbose_name_plural': 'Zgłoszenia grupowe (Групові заявки)',
                'ordering': ['-created_at'],
            },
        ),
    ]
