# Generated by Django 6.0.4 on 2026-04-20 10:51

import apps.cms.models
import django.db.models.deletion
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID właściciela (ID власника)')),
                ('kind', models.CharField(choices=[('text', 'Tekst / Nagłówek (Текст / Заголовок)'), ('image', 'Pojedynczy obraz (Окреме зображення)'), ('gallery', 'Galeria (Галерея)'), ('video', 'Wideo (Відео)'), ('form', 'Formularz (Форма)'), ('countdown', 'Timer odliczania (Таймер зворотного відліку)'), ('reviews', 'Opinie (Відгуки)'), ('related', 'Zobacz także (Дивіться також)'), ('cta', 'Przycisk / Banner (Кнопка / Банер)'), ('html', 'Surowy HTML (legacy) (Сирий HTML (legacy))')], db_index=True, max_length=20, verbose_name='Rodzaj bloku (Тип блоку)')),
                ('sort_order', models.IntegerField(db_index=True, default=0, verbose_name='Kolejność (Порядок)')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Widoczny (Видимий)')),
                ('css_anchor', models.SlugField(blank=True, help_text='Identyfikator HTML dla linków #anchor (HTML id для #anchor посилань)', max_length=80, verbose_name='Anchor (kotwica) (Якір (anchor))')),
                ('heading', models.CharField(blank=True, max_length=500, verbose_name='Nagłówek (Заголовок)')),
                ('heading_pl', models.CharField(blank=True, max_length=500, null=True, verbose_name='Nagłówek (Заголовок)')),
                ('heading_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='Nagłówek (Заголовок)')),
                ('heading_level', models.CharField(blank=True, choices=[('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], default='h2', max_length=2, verbose_name='Poziom nagłówka (Рівень заголовка)')),
                ('body', models.TextField(blank=True, verbose_name='Treść (Вміст)')),
                ('body_pl', models.TextField(blank=True, null=True, verbose_name='Treść (Вміст)')),
                ('body_en', models.TextField(blank=True, null=True, verbose_name='Treść (Вміст)')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='cms/blocks/', verbose_name='Obraz (Зображення)')),
                ('image_alt', models.CharField(blank=True, max_length=300, verbose_name='Tekst alternatywny (Альтернативний текст)')),
                ('image_alt_pl', models.CharField(blank=True, max_length=300, null=True, verbose_name='Tekst alternatywny (Альтернативний текст)')),
                ('image_alt_en', models.CharField(blank=True, max_length=300, null=True, verbose_name='Tekst alternatywny (Альтернативний текст)')),
                ('video_embed_url', models.URLField(blank=True, help_text='URL do osadzenia (YouTube /embed/…, Vimeo player.vimeo.com/…) (URL для вбудовування (YouTube /embed/…, Vimeo …))', max_length=500, verbose_name='URL osadzenia wideo (URL вбудовування відео)')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='cms/videos/', verbose_name='Plik wideo (Відеофайл)')),
                ('button_text', models.CharField(blank=True, max_length=200, verbose_name='Tekst przycisku (Текст кнопки)')),
                ('button_text_pl', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tekst przycisku (Текст кнопки)')),
                ('button_text_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tekst przycisku (Текст кнопки)')),
                ('button_url', models.CharField(blank=True, help_text='Pełny URL lub względna ścieżka (np. /vouchery/, #recenzje) (Повний URL або відносний шлях (напр. /vouchery/, #recenzje))', max_length=500, verbose_name='URL przycisku (URL кнопки)')),
                ('button_style', models.CharField(blank=True, choices=[('primary', 'Primary (Основна)'), ('outline', 'Outline (Контур)'), ('amber', 'Amber (Янтарна)')], default='primary', max_length=20, verbose_name='Styl przycisku (Стиль кнопки)')),
                ('countdown_target', models.DateTimeField(blank=True, null=True, verbose_name='Data docelowa odliczania (Цільова дата відліку)')),
                ('countdown_label', models.CharField(blank=True, max_length=200, verbose_name='Etykieta odliczania (Підпис відліку)')),
                ('countdown_label_pl', models.CharField(blank=True, max_length=200, null=True, verbose_name='Etykieta odliczania (Підпис відліку)')),
                ('countdown_label_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Etykieta odliczania (Підпис відліку)')),
                ('form_kind', models.CharField(blank=True, choices=[('contact', 'Formularz kontaktowy (Контактна форма)'), ('group', 'Zgłoszenie grupowe (Групова заявка)')], max_length=20, verbose_name='Rodzaj formularza (Тип форми)')),
                ('reviews_limit', models.PositiveSmallIntegerField(default=10, verbose_name='Limit opinii (Ліміт відгуків)')),
                ('related_strategy', models.CharField(blank=True, choices=[('manual', 'Ręcznie wybrane (Вибрано вручну)'), ('city', 'Według miasta (event) (За містом (подія))'), ('category', 'Według kategorii (event) (За категорією (подія))')], default='manual', max_length=20, verbose_name="Strategia 'Zobacz także' (Стратегія «Дивіться також»)")),
                ('related_limit', models.PositiveSmallIntegerField(default=6, verbose_name='Limit powiązanych (Ліміт пов’язаних)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(limit_choices_to=apps.cms.models._allowed_owner_models, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Typ właściciela (Тип власника)')),
            ],
            options={
                'verbose_name': 'Blok strony (Блок сторінки)',
                'verbose_name_plural': 'Bloki strony (konstruktor) (Блоки сторінки (конструктор))',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='cms/gallery/', verbose_name='Obraz (Зображення)')),
                ('image_url', models.URLField(blank=True, help_text='Zamiast pliku: bezpośredni URL obrazu (Замість файлу: пряме URL зображення)', max_length=500, verbose_name='URL obrazu (URL зображення)')),
                ('alt_text', models.CharField(blank=True, max_length=300, verbose_name='Tekst alternatywny (Альтернативний текст)')),
                ('alt_text_pl', models.CharField(blank=True, max_length=300, null=True, verbose_name='Tekst alternatywny (Альтернативний текст)')),
                ('alt_text_en', models.CharField(blank=True, max_length=300, null=True, verbose_name='Tekst alternatywny (Альтернативний текст)')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Kolejność (Порядок)')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_items', to='cms.pageblock', verbose_name='Blok galerii (Блок галереї)')),
            ],
            options={
                'verbose_name': 'Element galerii (Елемент галереї)',
                'verbose_name_plural': 'Elementy galerii (Елементи галереї)',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RelatedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_object_id', models.PositiveIntegerField(verbose_name='ID powiązanej strony (ID пов’язаної сторінки)')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Kolejność (Порядок)')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_items', to='cms.pageblock', verbose_name="Blok 'Zobacz także' (Блок «Дивіться також»)")),
                ('target_content_type', models.ForeignKey(limit_choices_to=apps.cms.models._allowed_owner_models, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Typ powiązanej strony (Тип пов’язаної сторінки)')),
            ],
            options={
                'verbose_name': 'Powiązana strona (Пов’язана сторінка)',
                'verbose_name_plural': 'Powiązane strony (Пов’язані сторінки)',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='pageblock',
            index=models.Index(fields=['content_type', 'object_id', 'sort_order'], name='cms_block_owner_order_idx'),
        ),
        migrations.AddIndex(
            model_name='pageblock',
            index=models.Index(fields=['kind'], name='cms_block_kind_idx'),
        ),
        migrations.AddIndex(
            model_name='relateditem',
            index=models.Index(fields=['target_content_type', 'target_object_id'], name='cms_related_target_idx'),
        ),
    ]
